// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://furqanali.vercel.app/",
            "email": "mirfurqan89@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fruits": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "fetch list of all available fruits",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fruits"
                ],
                "summary": "Fetch all fruits",
                "responses": {
                    "200": {
                        "description": "fruit list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/data.Fruit"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "add fruit info to stoed data",
                "produces": [
                    "applicaton/json"
                ],
                "tags": [
                    "fruits"
                ],
                "summary": "add fruit to fruits list",
                "parameters": [
                    {
                        "description": "fruit data",
                        "name": "fruit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.Fruit"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "fruit list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/data.Fruit"
                            }
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "unauthorized message",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/fruits/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get fruit info by id",
                "produces": [
                    "applicaton/json"
                ],
                "tags": [
                    "fruits"
                ],
                "summary": "fruits by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "get fruit by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "time stamp",
                        "schema": {
                            "$ref": "#/definitions/data.Fruit"
                        }
                    },
                    "401": {
                        "description": "unauthorized message",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Save User data",
                "produces": [
                    "applicaton/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "create user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "create response",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "error response",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "validate user and generate token",
                "produces": [
                    "applicaton/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create authentication token",
                "parameters": [
                    {
                        "description": "user email and password",
                        "name": "Authentication",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.Authentication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "422": {
                        "description": "invalid data",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/users/verify": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Authenticate user token",
                "produces": [
                    "applicaton/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Verify user token",
                "responses": {
                    "200": {
                        "description": "time stamp",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "unauthorized message",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "data.Authentication": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 7
                }
            }
        },
        "data.Fruit": {
            "type": "object",
            "required": [
                "currency",
                "name",
                "origin",
                "price"
            ],
            "properties": {
                "currency": {
                    "type": "string",
                    "enum": [
                        "usd",
                        "kd"
                    ]
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 4
                },
                "origin": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "data.User": {
            "type": "object",
            "required": [
                "age",
                "email",
                "name",
                "password",
                "phone",
                "role"
            ],
            "properties": {
                "age": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 7
                },
                "phone": {
                    "type": "integer",
                    "minimum": 10
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "manager",
                        "user"
                    ]
                }
            }
        },
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v0.1",
	Schemes:          []string{},
	Title:            "Go + Gin User API",
	Description:      "This is a sample server user server. You can visit the GitHub repository at https://github.com/Furqanalimir/commuter",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
