// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HelperSwaggerRequestResponse helper swagger request response
//
// swagger:model helper.SwaggerRequestResponse
type HelperSwaggerRequestResponse struct {

	// data
	Data string `json:"data,omitempty"`

	// error
	Error string `json:"error,omitempty"`
}

// Validate validates this helper swagger request response
func (m *HelperSwaggerRequestResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this helper swagger request response based on context it is used
func (m *HelperSwaggerRequestResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HelperSwaggerRequestResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HelperSwaggerRequestResponse) UnmarshalBinary(b []byte) error {
	var res HelperSwaggerRequestResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
